version: '2'

services:
  redis:
    image: sameersbn/redis:4.0.9-1
    command:
    - --loglevel warning
    restart: unless-stopped
    volumes:
    - gitlab-datastore:/var/lib/redis:Z
    networks:
    - letsencrypt_nginx-net

  postgresql:
    image: sameersbn/postgresql:9.6-2
    restart: unless-stopped
    volumes:
    - gitlab-db:/var/lib/postgresql:Z
    networks:
    - letsencrypt_nginx-net
    environment:
      DB_USER: gitlab
      DB_PASS: "${DB_PASS}"
      DB_NAME: gitlabhq_production
      DB_EXTENSION: pg_trgm

  gitlab:
    image: sameersbn/gitlab:11.3.4
    restart: unless-stopped
    depends_on:
    - redis
    - postgresql
    volumes:
    - gitlab-data:/home/git/data:Z
    networks:
    - letsencrypt_nginx-net
    environment:
      DEBUG: "false"

      DB_ADAPTER: postgresql
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: gitlab
      DB_PASS: "${DB_PASS}"
      DB_NAME: gitlabhq_production

      REDIS_HOST: redis
      REDIS_PORT: 6379

      TZ: Europe/Paris
      GITLAB_TIMEZONE: Paris

      GITLAB_HTTPS: "true"
      SSL_SELF_SIGNED: "false"

      GITLAB_HOST: "${GITLAB_DOMAIN}"
      # GITLAB_PORT: 80 # port to generate URLs
      GITLAB_SSH_PORT: 22 # port to generate URLs
      GITLAB_RELATIVE_URL_ROOT: 
      GITLAB_SECRETS_DB_KEY_BASE: "${GITLAB_SECRETS_DB_KEY_BASE}"
      GITLAB_SECRETS_SECRET_KEY_BASE: "${GITLAB_SECRETS_SECRET_KEY_BASE}"
      GITLAB_SECRETS_OTP_KEY_BASE: "${GITLAB_SECRETS_OTP_KEY_BASE}"

      # admin user
      GITLAB_ROOT_EMAIL: "admin@${EMAIL_DOMAIN}"
      GITLAB_ROOT_PASSWORD: "${GITLAB_ROOT_PASSWORD}"

      GITLAB_NOTIFY_ON_BROKEN_BUILDS: "true"
      GITLAB_NOTIFY_PUSHER: "false"

      GITLAB_BACKUP_SCHEDULE: daily
      GITLAB_BACKUP_TIME: 01:00

      # email configuration
      GITLAB_EMAIL: "gitlab@${EMAIL_DOMAIN}"
      GITLAB_EMAIL_REPLY_TO: "noreply@${EMAIL_DOMAIN}"
      GITLAB_INCOMING_EMAIL_ADDRESS: "reply@${EMAIL_DOMAIN}"
      GITLAB_EMAIL_DISPLAY_NAME: Gitlab
      SMTP_ENABLED: "false"
      SMTP_DOMAIN: "${EMAIL_DOMAIN}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: 587
      SMTP_USER: "gitlab@${EMAIL_DOMAIN}"
      SMTP_PASS: "${EMAIL_PASS}"
      SMTP_STARTTLS: "true"
      SMTP_AUTHENTICATION: login

      IMAP_ENABLED: "false"
      IMAP_HOST: "${IMAP_HOST}"
      IMAP_PORT: 993
      IMAP_USER: "gitlab@${EMAIL_DOMAIN}"
      IMAP_PASS: "${EMAIL_PASS}"
      IMAP_SSL: "true"
      IMAP_STARTTLS: "false"

      OAUTH_ENABLED: "false"
      OAUTH_AUTO_SIGN_IN_WITH_PROVIDER: 
      OAUTH_ALLOW_SSO: 
      OAUTH_BLOCK_AUTO_CREATED_USERS: "true"
      OAUTH_AUTO_LINK_LDAP_USER: "false"
      OAUTH_AUTO_LINK_SAML_USER: "false"
      OAUTH_EXTERNAL_PROVIDERS: 

      OAUTH_CAS3_LABEL: cas3
      OAUTH_CAS3_SERVER: 
      OAUTH_CAS3_DISABLE_SSL_VERIFICATION: "false"
      OAUTH_CAS3_LOGIN_URL: /cas/login
      OAUTH_CAS3_VALIDATE_URL: /cas/p3/serviceValidate
      OAUTH_CAS3_LOGOUT_URL: /cas/logout

      OAUTH_GOOGLE_API_KEY: "${OAUTH_GOOGLE_API_KEY}"
      OAUTH_GOOGLE_APP_SECRET: "${OAUTH_GOOGLE_APP_SECRET}"
      OAUTH_GOOGLE_RESTRICT_DOMAIN: 

      OAUTH_FACEBOOK_API_KEY: "${OAUTH_FACEBOOK_API_KEY}"
      OAUTH_FACEBOOK_APP_SECRET: "${OAUTH_FACEBOOK_APP_SECRET}"

      OAUTH_TWITTER_API_KEY: "${OAUTH_TWITTER_API_KEY}"
      OAUTH_TWITTER_APP_SECRET: "${OAUTH_TWITTER_APP_SECRET}"

      OAUTH_GITHUB_API_KEY: "${OAUTH_GITHUB_API_KEY}"
      OAUTH_GITHUB_APP_SECRET: "${OAUTH_GITHUB_APP_SECRET}"
      OAUTH_GITHUB_URL:
      OAUTH_GITHUB_VERIFY_SSL: "${OAUTH_GITHUB_VERIFY_SSL}"

      OAUTH_GITLAB_API_KEY: "${OAUTH_GITLAB_API_KEY}"
      OAUTH_GITLAB_APP_SECRET: "${OAUTH_GITLAB_APP_SECRET}"

      OAUTH_BITBUCKET_API_KEY: "${OAUTH_BITBUCKET_API_KEY}"
      OAUTH_BITBUCKET_APP_SECRET: "${OAUTH_BITBUCKET_APP_SECRET}"

      OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL: 
      OAUTH_SAML_IDP_CERT_FINGERPRINT: 
      OAUTH_SAML_IDP_SSO_TARGET_URL: 
      OAUTH_SAML_ISSUER: 
      OAUTH_SAML_LABEL: "Our SAML Provider"
      OAUTH_SAML_NAME_IDENTIFIER_FORMAT: urn:oasis:names:tc:SAML:2.0:nameid-format:transient
      OAUTH_SAML_GROUPS_ATTRIBUTE: 
      OAUTH_SAML_EXTERNAL_GROUPS: 
      OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL: 
      OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME: 
      OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME: 
      OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME: 

      OAUTH_CROWD_SERVER_URL: 
      OAUTH_CROWD_APP_NAME: 
      OAUTH_CROWD_APP_PASSWORD: "${OAUTH_CROWD_APP_PASSWORD}"

      OAUTH_AUTH0_CLIENT_ID: "${OAUTH_AUTH0_CLIENT_ID}"
      OAUTH_AUTH0_CLIENT_SECRET: "${OAUTH_AUTH0_CLIENT_SECRET}"
      OAUTH_AUTH0_DOMAIN:

      OAUTH_AZURE_API_KEY: "${OAUTH_AZURE_API_KEY}"
      OAUTH_AZURE_API_SECRET: "${OAUTH_AZURE_API_SECRET}"
      OAUTH_AZURE_TENANT_ID: "${OAUTH_AZURE_TENANT_ID}"


volumes:
  gitlab-datastore:
    driver: local
  gitlab-db:
    driver: local
  gitlab-data:
    driver: local

networks:
  letsencrypt_nginx-net:
    external: true